### ISSUE TITLE
What's the purpose of this repo?

### ISSUE THREAD

**Issue by tomayac** [explainers-by-googlers/.allstar#1]
FYI: @jyasskin.

**Comment by jyasskin** [comment]
Google's OSPO put it here as a place to configure https://github.com/ossf/allstar, but the tool doesn't seem very active, so I'm worried about enabling what might be a failed experiment. The policies it can enforce also aren't very useful for an explainers org. I've been letting the repo sit around until OSPO figures out what they want to do with it. I can archive it to get it out of the way, though.
